### PR TITLE
use a local path rather than an absolute path for the source map link

### PR DESCRIPTION
**Pull request by BrandonOCasey**

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thanks @BrandonOCasey!

**Comment by paulmelnikow** [comment]
Thanks for this easy solution to the source maps problem.

I'm using a relative path and ran into this issue too. Could you release an update to npm?

**Comment by bigtimebuddy** [comment]
@paulmelnikow & @BrandonOCasey release has been made (v1.0.1)

**Comment by paulmelnikow** [comment]
Awesome. Thanks!

**Pull request merged**
